### ISSUE TITLE
Add functions `[MotrpacRatTraining6mo::cluster_pathway_enrichment()]` and `[MotrpacRatTraining6mo::run_fella()]`

### ISSUE THREAD

**Issue by biodavidjm** [MoTrPAC/MotrpacRatTraining6moData#11]
Reminder:

> Not sure how to fix the first line, but for the second line, cluster_pathway_enrichment and run_fella are functions we plan to add but have not yet added to MotrpacRatTraining6mo. Can you replace them with [MotrpacRatTraining6mo::cluster_pathway_enrichment()] and [MotrpacRatTraining6mo::run_fella()] and add an issue to MotrpacRatTraining6mo to add these functions and assign me?

The issue will go away as soon as you add the functions to the package

**Comment by nicolerg** [comment]
These functions should be added to https://github.com/MoTrPAC/MotrpacRatTraining6mo, not this package. I'll reference this issue there.

**Comment by nicolerg** [comment]
Added in https://github.com/MoTrPAC/MotrpacRatTraining6mo/pull/19. I will close this issue once the MotrpacRatTraining6mo package is public

**Comment by nicolerg** [comment]
resolved by #24
