### ISSUE TITLE
force Roxgyen to keep suggested packages 

### ISSUE THREAD

**Issue by nicolerg** [MoTrPAC/MotrpacRatTraining6moData#15]
Right now I want `Suggests` in `DESCRIPTION` to include:

- `data.table`
- `tidyverse`
- `MotrpacBicQC`

We can discuss if it is necessary to include any of these. `tidyverse` is probably the only one that should be there because of the current format of `METAB_SAMPLE_DATA_NESTED`

**Comment by nicolerg** [comment]
> ❯ checking Rd cross-references ... WARNING
>   Packages unavailable to check Rd xrefs: ‘limma’, ‘ChIPseeker’, ‘gprofiler2’, ‘FELLA’, ‘IHW’, ‘preprocessCore’, ‘KEGGREST’, ‘edgeR’

This just means these packages aren't installed in the version of R where I ran the check, but should we also add all of these packages to Suggests in DESCRIPTION @biodavidjm?

**Comment by nicolerg** [comment]
fixed in https://github.com/MoTrPAC/MotrpacRatTraining6moData/commit/3ff7465fd3c0bea0bad11c6faf994e14468e4c5e

**Comment by bcjaeger** [comment]
It may not be a good idea to include `tidyverse` in the suggested packages of `DESCRIPTION`. There are over 75 dependencies for the `tidyverse` package, which means those 75+ packages will need to be installed when users install your package, which could increase installation time. There is a nice note by Hadley Wickham and Mara Averick here: https://www.tidyverse.org/blog/2018/06/tidyverse-not-for-packages/. 

Would including `tibble` as a suggested package be helpful?

**Comment by nicolerg** [comment]
@bcjaeger good to know, thank you! yes, `tibble` would work. do you know happen to know how `roxygen2` decides to put things in `Suggests` or `Imports` in the `DESCRIPTION`?

**Comment by bcjaeger** [comment]
No problem! Excellent question. 

- As far as I know, `roxygen2` does not modify these fields in `DESCRIPTION`, but it does modify `NAMESPACE` based on `roxygen2` commands like `#' @import data.table` in your package documentation script (see `?usethis::use_package_doc`).   

- `usethis::use_package()` _does modify_ `DESCRIPTION` by adding a package to whichever field you indicate. 

General workflow for this is

1. `usethis::use_package()` to put the package into `DESCRIPTION` (you can also just manually type it)
2. `devtools::document()` to make `roxygen2` update `NAMESPACE`
3. `devtools::check()` to make sure all the packages that your package needs are accounted for in `DESCRIPTION`. 

I haven't talked about the difference between suggested packages and imported packages. You can find more about that here: https://r-pkgs.org/dependencies.html. 

> should we also add all of these packages to Suggests in DESCRIPTION?

I believe the answer to this question is yes. 

- putting a package into the `suggests` field indicates that the package should be installed when your package is built in a new environment. 
- For example, if your package uses another package in an example, or a vignette, or a test, then that package isn't _needed_ for someone to use your package but it _is needed_ to run examples in your documentation, or vignettes, or run your tests, so it should be present when your package is built in a new environment.

**Comment by nicolerg** [comment]
Thanks @bcjaeger, that's very helpful!

I am going to change the format of `METAB_SAMPLE_DATA_NESTED` from a tibble to a data frame to avoid any required packages/imports for this package. 

For suggested packages, I think we should include packages that are linked in the documentation:
- limma
- ChIPseeker
- gprofiler2
- FELLA
- IHW
- preprocessCore
- KEGGREST
- edgeR
- MotrpacBicQC
- MotrpacRatTraining6moData

or used in `inst/scripts`:
- data.table
- dplyr
- testit
- usethis
- sinew
- devtools

Does that make sense?
