### ISSUE TITLE
reduce size of repo by removing old versions of data

### ISSUE THREAD

**Issue by nicolerg** [MoTrPAC/MotrpacRatTraining6moData#17]
@bcjaeger @biodavidjm I don't see a reason for keeping all of the tracked versions of files in `data/*`, and it is making the repo large. Can we delete history for all of these files? Is there a reason not to do this? Are you aware of the easiest way to do this?

Note there are a couple of branches to merge before doing this.

**Comment by bcjaeger** [comment]
That is a great idea. We can always dig through snapshots from past commits if we ever need to get old versions of these files. I'm flying home today but I'll check this out when I can and try to give some more specific thoughts.

**Comment by nicolerg** [comment]
Thanks, @bcjaeger! This also applies to commit history of scripts in `inst/scripts` that had full paths on my cluster, which can be a security issue. I just removed those paths in the last PR but the commit history still has the paths. 

A couple starting points:
- https://stackoverflow.com/questions/6358476/how-to-remove-old-versions-of-media-files-from-a-git-repository
- https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository

**Comment by bcjaeger** [comment]
No problem at all, happy to help!

As far as the previous commits go, I have been there, and my old-school fix was deleting the GitHub remote and starting a new one. Let's not do that =] 

I like BFG (https://rtyley.github.io/bfg-repo-cleaner/) since it seems like the easiest option to apply and should be able to do the job of scrubbing previous commits for us. I haven't used it before, but I can test it out on some dummy repos and report back.

**Comment by biodavidjm** [comment]
I have never done this or, if I did, I am afraid it was following the old school method mentioned by @bcjaeger ;-)

Please @bcjaeger, go ahead with the proposed solution

**Comment by nicolerg** [comment]
To be fair, if we’re asking to remove history from everything in `data/` and everything in `inst/scripts`, that’s pretty much the entire repository… It would be one thing if we only wanted to remove history for a couple of files, but maybe the old-school method isn’t actually the worst solution in this case?

On Aug 12, 2022, at 10:56 PM, David JM ***@***.***> wrote:

﻿

I have never done this or, if I did, I am afraid it was following the old school method mentioned by @bcjaeger<https://github.com/bcjaeger> ;-)

Please @bcjaeger<https://github.com/bcjaeger>, go ahead with the proposed solution

**Comment by bcjaeger** [comment]
That is definitely fair, and the old school method will be much faster than learning how to use BFG, even though BFG seems like the simplest tool to use.

The only thing that I'm hesitant about would be losing the history of issues and pull requests. It is sometimes helpful to be able to pull the history up from a closed issue or a previous commit or merge from a pull request.  

@nicolerg - you know the full history of this repo. Would you be comfortable losing its data on issues, releases, pull requests, and all the other things GitHub tracks? If we want to keep all of that, I think BFG is our best path forward.

**Comment by nicolerg** [comment]
Hmm that’s true. I would like to keep the issues. Are you okay with learning/implementing BFG? I agree it seems like the easiest solution but even then doesn’t seem that simple.

On Aug 13, 2022, at 11:27 AM, Byron ***@***.***> wrote:

﻿

That is definitely fair, and the old school method will be much faster than learning how to use BFG, even though BFG seems like the simplest tool to use.

The only thing that I'm hesitant about would be losing the history of issues and pull requests. It is sometimes helpful to be able to pull the history up from a closed issue or a previous commit or merge from a pull request.

@nicolerg<https://github.com/nicolerg> - you know the full history of this repo. Would you be comfortable losing its data on issues, releases, pull requests, and all the other things GitHub tracks? If we want to keep all of that, I think BFG is our best path forward.

**Comment by bcjaeger** [comment]
Definitely! Cleaning unwanted data out of commit history is probably a skill I will use at least once in my future, unfortunately.

**Comment by bcjaeger** [comment]
Do we want to remove the history for every file in  `data/` and every file in `inst/scripts`, or just a specific subset of files?

**Comment by nicolerg** [comment]
Everything in `data/` and all scripts in `inst/scripts` except your compression script

On Aug 13, 2022, at 12:39 PM, Byron ***@***.***> wrote:

﻿

Do we want to remove the history for every file in data/ and every file in inst/scripts, or just a specific subset of files?

**Comment by bcjaeger** [comment]
Good news - I think I've got a version of the repo that I can push to the main branch and wipe away the history we don't want.

However, before I do something so permanent, I'd like to ask for a review of the repo I made here: https://github.com/bcjaeger/MotrpacRatTraining6moData 

- You should see the data directory present in the most recent commit but wiped from all previous commits. (I left the data in the most recent commit because I think we want to have the data in the repo, just not all the past versions of it. If that's incorrect, I can also wipe the data from the most recent commit). 

- You should also see nothing but `compress_data.R` in `inst/scripts`, both in the most recent commit and all previous ones.

If my repo makes sense and is the version of the repo that we want to move forward with, I believe I can force push it to the main branch and in doing so re-write the commit history of the main branch. The only thing then would be to make sure anyone who had a previous copy of the repo on their local machine does `git rebase` from the main branch to overwrite their local history with the remote's history.

**Comment by nicolerg** [comment]
Thanks, @bcjaeger! One important correction - the other scripts in `inst/scripts` in the main branch of this repo should also be in your branch, just with past commits scrubbed, like the data files. I still want the scripts there but without the sensitive paths I removed in a recent commit. Does that make sense?

Is force pushing to the main branch the only way to apply the changes? I will have to change your permissions and remove protection from the main branch if that's the case.

**Comment by bcjaeger** [comment]
No problem at all - good catch on the scripts, that makes perfect sense.

I am guessing that I need to force push (if it isn't forced, GitHub rejects the commits b/c they conflict with the remote's history), but perhaps it's also possible to do this with a pull request? It shouldn't cause any problems to at least try.

I will add the scripts back into `inst/scripts` with file paths replaced by blanks, then try to initiate a pull request.

**Comment by nicolerg** [comment]
Instead of replacing file paths with blanks, can you just add the current versions of scripts in `inst/scripts` to your branch? I already modified the file paths to how I would like them to stay.

**Comment by bcjaeger** [comment]
Definitely - much easier to do that. Thanks =]

**Comment by nicolerg** [comment]
From steps 8 and 9 [here](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository), it looks like you will need to force-push the repos _and_ tags
```
git push origin --force --all
git push origin --force --tags
```

**Comment by bcjaeger** [comment]
That site is fantastic. I'm not sure if steps 8 and 9 apply to the BFG version of things, but maybe it's safe to assume that force pushing the tags is a good idea anyway.

**Comment by nicolerg** [comment]
Ah true. In the [BFG section](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository#using-the-bfg) it also says you must force push your changes to GitHub (though the command they use is just `git push --force`). Let's try the above two commands. 

I'm not too familiar with tags and probably complicated things by adding them in this case...

Let me know when you've updated your repo and I'll change your write permissions.

**Comment by bcjaeger** [comment]
Got it! I tried opening the pull request but I'm guessing it will ask you to manually resolve all of the conflicts. 

I'm happy to do the force push instead. My repo has the scripts back into `inst/scripts` now

**Comment by bcjaeger** [comment]
You've probably already done this, but keeping a local copy backed up on your computer with the current version of files from your main branch will be a good way to provide some insurance in case I messed something up in the branch that I am about to push over. Can never be too safe.

**Comment by nicolerg** [comment]
Your repo looks good! You should have permission to force push now

**Comment by bcjaeger** [comment]
Awesome. Push is in progress now.

**Comment by nicolerg** [comment]
Looks good! You are now listed as the only contributor for objects in `inst/scripts/` and `data/`, but it got the job done. Thank you for figuring out BFG! https://github.com/MoTrPAC/MotrpacRatTraining6moData/commit/ee9c6266c42ac9f26286a91bcbf1f9e7dd279453

**Comment by bcjaeger** [comment]
> You are now listed as the only contributor for objects in inst/scripts/ and data/

Well, that seems unfair. =/ 

Glad it worked! I would like to have my pushing privileges to the main branch taken back to require approval, just to make sure I don't break anything in the future. But, before we do that, I noticed one of the more recent commits has files in the `inst/script` has files in it that should have been wiped. Is it okay with you if I do one more force push to wipe those?

**Comment by nicolerg** [comment]
Are you sure? I looked at the commit history for scripts in `inst/scripts` and didn't see any of the sensitive paths in the oldest commit.

**Comment by nicolerg** [comment]
I also deleted the tags since there was no need for them and the paths were still included in the tarballs associated with the tags.

**Comment by bcjaeger** [comment]
I think so - checkout commit bc06752c8523c5deda6b92eff3bbc272e0e8b79f and the files are still there.

> I also deleted the tags

Got it, makes sense. I liked the name of the release though!

**Comment by nicolerg** [comment]
>I think so - checkout commit https://github.com/MoTrPAC/MotrpacRatTraining6moData/commit/bc06752c8523c5deda6b92eff3bbc272e0e8b79f and the files are still there.

The files in this commit are identical to the current version though (they don't include the sensitive paths starting from root in the setup chuck) so I think this is fine.

**Comment by bcjaeger** [comment]
Ah, fantastic! I think we are good then =]

**Comment by nicolerg** [comment]
Great, thanks! Can you delete your fork of the repo? I will ask Pierre to do the same.

**Comment by bcjaeger** [comment]
You bet! Just deleted it.

**Comment by biodavidjm** [comment]
I guess we all should delete and clone again
