### ISSUE TITLE
Incorrect metabolomics sample labels

### ISSUE THREAD

**Issue by TylerSagendorf** [MoTrPAC/MotrpacRatTraining6moData#36]
The sample names in `METAB_NORM_DATA_NESTED/FLAT` appear to have been shuffled, at least for WAT-SC. Below is a plot of "TG(36:2)>TG(2:0_16:0_18:2)_feature4", a metabolite that had been shown to be sexually dimorphic in the WAT companion paper. Notice that there appears to be two distinct groups of values, though they are randomly assigned to each group. I am not sure if this issue extends to what is in the Data Hub.

<img src="https://user-images.githubusercontent.com/57922480/207415404-45a68ce3-d9e1-4392-b72c-9111f1212b74.png" width=60% height=60%>

**Comment by nicolerg** [comment]
Hi Tyler, can you please share the code snippet used to generate this plot?

**Comment by TylerSagendorf** [comment]
> Hi Tyler, can you please share the code snippet used to generate this plot?

Here is the R script and an additional file that you will need on line 39. Code for plot is at the end.

[metab_tmp_data.txt](https://github.com/MoTrPAC/MotrpacRatTraining6moData/files/10221659/metab_tmp_data.txt)

```
library(MotrpacRatTraining6moData)
library(dplyr)
library(tibble)
library(MSnbase)
library(ggplot2)

## Remove redundant metabolites ----

# Better names (is there an easier way to do this?)
new_refmet <- c(
  "Car(16:1)_feature1" = "CAR 16:1 (1)",
  "Car(16:1)" = "CAR 16:1 (2)",
  "C18:1 carnitine" = "CAR 18:1 (1)",
  "Car(18:1)_feature1" = "CAR 18:1 (2)",
  "C18:2 carnitine" = "CAR 18:2 (1)",
  "Car(18:2)_feature1" = "CAR 18:2 (2)",
  "C4 carnitine" = "CAR 4:0 (1)",
  "Car(4:0)" = "CAR 4:0 (2)",
  "C5 carnitine" = "CAR 5:0 (1)",
  "Car(5:0)" = "CAR 5:0 (2)",
  "C3-DC-CH3 carnitine" = "CAR 3:0;2Me (1)",
  "Car(3:0, 2-CH3)" = "CAR 3:0;2Me (2)",

  "TG(36:1)>TG(8:0_10:0_18:1)_and_TG(10:0_10:0_16:1)_feature3" = "TG 36:1 iso1",
  "TG(36:1)>TG(4:0_16:0_16:1)_and_TG(2:0_16:0_18:1)_feature4" = "TG 36:1 iso2",
  "TG(36:1)>TG(4:0_16:0_16:1)_and_TG(2:0_16:0_18:1)_M+NH3_feature1" = "TG 36:1 iso3",
  "TG(38:0)>TG(10:0_12:0_16:0)_and_TG(10:0_10:0_18:0)_and_TG(8:0_12:0_18:0)_M+NH3_feature3" = "TG 38:0 iso1",
  "TG(38:0)>TG(10:0_12:0_16:0)_and_TG(10:0_10:0_18:0)_and_TG(8:0_12:0_18:0)_M+NH3_feature2" = "TG 38:0 iso2",
  "TG(38:0)>TG(10:0_12:0_16:0)_and_TG(10:0_10:0_18:0)_and_TG(8:0_12:0_18:0)_M+NH3_feature1" = "TG 38:0 iso3",
  "TG(38:1)>TG(10:0_10:0_18:1)_and_TG(10:0_12:0_16:1)_and_TG(8:0_12:0_18:1)_feature2" = "TG 38:1 iso1",
  "TG(38:1)>TG(4:0_16:0_18:1)_feature3" = "TG 38:1 iso2",
  "TG(38:1)>TG(10:0_10:0_18:1)_and_TG(10:0_12:0_16:1)_and_TG(8:0_12:0_18:1)_M+NH3_feature1" = "TG 38:1 iso3",
  "TG(38:2)>TG(10:0_10:0_18:2)_and_TG(8:0_12:0_18:2)_feature2" = "TG 38:2 iso1",
  "TG(38:2)>TG(4:0_16:1_18:1)_and_TG(4:0_16:0_18:2)_feature3" = "TG 38:2 iso2",
  "TG(38:2)>TG(4:0_16:1_18:1)_and_TG(4:0_16:0_18:2)_M+NH3_feature1" = "TG 38:2 iso3"
)

# Pre-filtered data with additional columns
refmet_df <- read.delim("./data-raw/metab_tmp_data.txt") %>%
  mutate(feature = feature_ID) %>%
  # isomers: 50:5, 56:6
  mutate(name_in_figures = ifelse(CURRENT_REFMET_NAME %in% names(new_refmet),
                                  new_refmet[CURRENT_REFMET_NAME],
                                  CURRENT_REFMET_NAME)) %>%
  select(feature_ID, dataset, name_in_figures, lipid_class:sub_class) %>%
  dplyr::rename(refmet_super_class = super_class,
                refmet_main_class = main_class,
                refmet_sub_class = sub_class) %>%
  `rownames<-`(.[["feature_ID"]])

refmet_df[refmet_df == ""] <- NA

# Phenodata
p_data <- PHENO %>%
  filter(tissue == "WAT-SC",
         biclabeldata.shiptositeid == "emory sub - georgia tech") %>%
  select(pid:viallabel, sex, timepoint = group) %>%
  mutate(sex = factor(sex,
                      levels = c("female", "male"),
                      labels = c("Female", "Male")),
         timepoint = ifelse(timepoint == "control", "SED",
                            toupper(timepoint)),
         timepoint = factor(timepoint,
                            levels = c("SED", paste0(2^(0:3), "W"))),
         exp_group = paste(substr(sex, 1, 1), timepoint, sep = "_")) %>%
  arrange(sex, timepoint) %>%
  mutate(exp_group = factor(exp_group, levels = unique(exp_group))) %>%
  `rownames<-`(.[["pid"]])

not_all_NA <- function(x) {
  !all(is.na(x))
}

# Normalized expression data
expr_mat <- METAB_NORM_DATA_FLAT %>%
  filter(tissue == "WAT-SC") %>%
  inner_join(select(refmet_df, feature_ID, dataset),
             by = c("feature_ID", "dataset")) %>%
  column_to_rownames("feature_ID") %>%
  select(-c(dataset, tissue, feature, assay)) %>%
  select(where(not_all_NA)) %>%
  as.matrix() %>%
  .[rownames(refmet_df), rownames(p_data)]

# Create MSnSet
METAB_MSNSET <- MSnSet(exprs = expr_mat, fData = refmet_df, pData = p_data)

# Use viallabel instead of pid
sampleNames(METAB_MSNSET) <- METAB_MSNSET$viallabel

# Save
# usethis::use_data(METAB_MSNSET, internal = FALSE, overwrite = TRUE,
#                   version = 3, compress = "bzip2")


# Check plots --------------------------------------------------------------
m1 <- METAB_MSNSET # shorter name

m1$tmp <- exprs(m1)["TG(36:2)>TG(2:0_16:0_18:2)_feature4", ]

ggplot(pData(m1)) +
  geom_point(aes(x = timepoint, y = tmp),
             position = ggbeeswarm::position_beeswarm(cex = 3, groupOnX = T)) +
  facet_wrap(~ sex) +
  labs(y = "TG(36:2)>TG(2:0_16:0_18:2)_feature4",
       x = NULL) +
  theme_bw()

```

**Comment by nicolerg** [comment]
Thank you for identifying and reporting this. I checked with a parallel approach and also see that the PIDs in `METAB_NORM_DATA_FLAT` are shuffled relative to the viallabels in the data freeze, at least for WAT-SC metab-u-lrppos. I am working on figuring out far up this goes. 

This error could have been introduced in one of two places: 
1. Collecting sample-level data to perform differential analysis here, in which case all differential analysis results are affected: https://github.com/MoTrPAC/motrpac-bic-norm-qc/blob/master/bic_qc_reports/inprogress/pass1b_metabolomics_dea.Rmd
2. Converting the nested sample-level data to the flat table here, in which case only `METAB_NORM_DATA_FLAT` is affected: https://github.com/MoTrPAC/MotrpacRatTraining6moData/blob/main/inst/scripts/save_sample_level_data_metabolomics.Rmd

Adding @pierremj and @biodavidjm to this issue. Pierre, David, any thoughts on the quickest way to figure out where this error was introduced?

Attached is the script I used to confirm the viallabel swapping.
[check-metab-vl.R.zip](https://github.com/MoTrPAC/MotrpacRatTraining6moData/files/10222630/check-metab-vl.R.zip)

**Comment by nicolerg** [comment]
@TylerSagendorf can you see if you get the expected results using `METAB_NORM_DATA_NESTED` instead of `METAB_NORM_DATA_FLAT`? So far it looks like `METAB_NORM_DATA_NESTED` matches the data in the freeze, and the PIDs in `METAB_NORM_DATA_FLAT` are shuffled relative to viallabels in `METAB_NORM_DATA_NESTED`. Still investigating.

**Comment by nicolerg** [comment]
This is what I get using `METAB_NORM_DATA_NESTED`, so I think these data are correct:
![plot](https://user-images.githubusercontent.com/32148717/207470107-dbee94aa-6165-4db0-9498-28e24c636b27.png)

Here's the code to reproduce the plot:
```
library(MotrpacRatTraining6moData)
library(ggplot2)

nested_wat = METAB_NORM_DATA_NESTED$`metab-u-lrppos`$`WAT-SC`
feature = melt(nested_wat["TG(36:2)>TG(2:0_16:0_18:2)_feature4",], variable.name="viallabel")
# merge with pheno
feature = merge(feature, PHENO[,c("viallabel","sex","group")], by="viallabel")
# plot 
ggplot(feature, aes(x=group, y=value)) +
  geom_point() +
  facet_wrap(~ sex) +
  labs(title="WAT TG(36:2)>TG(2:0_16:0_18:2)_feature4")
```

**Comment by TylerSagendorf** [comment]
> ```
> library(MotrpacRatTraining6moData)
> library(ggplot2)
> 
> nested_wat = METAB_NORM_DATA_NESTED$`metab-u-lrppos`$`WAT-SC`
> feature = melt(nested_wat["TG(36:2)>TG(2:0_16:0_18:2)_feature4",], variable.name="viallabel")
> # merge with pheno
> feature = merge(feature, PHENO[,c("viallabel","sex","group")], by="viallabel")
> # plot 
> ggplot(feature, aes(x=group, y=value)) +
>   geom_point() +
>   facet_wrap(~ sex) +
>   labs(title="WAT TG(36:2)>TG(2:0_16:0_18:2)_feature4")
> ```

@nicolerg This only works if you look at one dataset from `METAB_NORM_DATA_NESTED`. To combine all of the data for a single tissue, I had to convert from viallabel to bid so that samples would match between platforms (I call this "dataset"). If you replace the part where I create `expr_data` in my previous code with the snippet below, this is the plot that I get. This also matches with the data I had been using for all of the analyses.

```
library(tidyr)
library(dplyr)
library(tibble)

vial_to_bid <- select(PHENO, viallabel, bid) %>%
  mutate(across(.fns = as.character)) %>%
  deframe()

expr_mat <- METAB_NORM_DATA_NESTED %>%
  lapply(function(xi) {
    xi <- xi[["WAT-SC"]]
    # If we don't switch from viallabels to bid,
    # none of the datasets will have the same column names,
    # and we will end up with 200+ columns
    colnames(xi) <- vial_to_bid[colnames(xi)]

    rownames_to_column(xi, "feature_ID")
  }) %>%
  enframe(name = "dataset") %>%
  unnest(value) %>%
  inner_join(select(refmet_df, feature_ID, dataset),
             by = c("feature_ID", "dataset")) %>%
  column_to_rownames("feature_ID") %>%
  select(-dataset) %>%
  as.matrix() %>%
  .[refmet_df$feature_ID, rownames(p_data)] # reordering
```

<img src="https://user-images.githubusercontent.com/57922480/207478620-7a1af933-4a58-4416-9588-dbda68d143da.png" height="60%" width="60%">

**Comment by nicolerg** [comment]
@TylerSagendorf Thanks for checking. I understand the structure of `METAB_NORM_DATA_NESTED` is different than what you wanted in your code, but I wanted to make sure you got the expected results using those data. I am working on pushing corrected `METAB_NORM_DATA_FLAT`, which is the preferred format for your code. 

>To combine all of the data for a single tissue, I had to convert from viallabel to bid so that samples would match between platforms (I call this "dataset").

Yes, this is effectively what `METAB_NORM_DATA_FLAT` is, except we convert to PID instead of BID.

**Comment by TylerSagendorf** [comment]
@nicolerg Oh I didn't catch that the ordering of the x-axis was different in our plots, but the data being shown is the same. Sorry for the misunderstanding, and thanks for taking care of this so quickly!

**Comment by nicolerg** [comment]
@TylerSagendorf Sorry for the confusion - I rushed the plotting. Thank you so much for catching this! The same bug affected `IMMUNO_NORM_DATA_FLAT`, so I fixed both and will merge the changes with the main branch as soon as the R-CMD-check workflow runs without error.

**Comment by nicolerg** [comment]
@TylerSagendorf Please reinstall this package to get the newest version. `METAB_NORM_DATA_FLAT` and `METAB_NORM_DATA_NESTED` now have the same data/sample IDs. Here's an example for a single feature, where the plots are identical (same as the plot I shared above):

```r
library(MotrpacRatTraining6moData)
library(ggplot2)
library(data.table)

# with METAB_NORM_DATA_FLAT
metab_data = data.table(METAB_NORM_DATA_FLAT)
feature = melt(metab_data[feature_ID == "TG(36:2)>TG(2:0_16:0_18:2)_feature4"],
               measure.vars = colnames(metab_data)[grepl("^1", colnames(metab_data))],
               id.vars = c("feature_ID"),
               variable.name = "pid")
# remove NA
feature = feature[complete.cases(feature)]
# merge with pheno
PHENO$pid = as.character(PHENO$pid)
feature[,pid := as.character(pid)]
feature = merge(feature, unique(PHENO[,c("pid","sex","group")]), by="pid")
# plot 
ggplot(feature, aes(x=group, y=value)) +
  geom_point() +
  facet_wrap(~ sex) +
  labs(title="WAT TG(36:2)>TG(2:0_16:0_18:2)_feature4")

# with METAB_NORM_DATA_NESTED
nested_wat = METAB_NORM_DATA_NESTED$`metab-u-lrppos`$`WAT-SC`
feature = melt(nested_wat["TG(36:2)>TG(2:0_16:0_18:2)_feature4",], variable.name="viallabel")
# merge with pheno
feature = merge(feature, PHENO[,c("viallabel","sex","group")], by="viallabel")
# plot 
ggplot(feature, aes(x=group, y=value)) +
  geom_point() +
  facet_wrap(~ sex) +
  labs(title="WAT TG(36:2)>TG(2:0_16:0_18:2)_feature4")
```
