### ISSUE TITLE
Minor typo in `PHENO` documentation

### ISSUE THREAD

**Issue by TylerSagendorf** [MoTrPAC/MotrpacRatTraining6moData#40]
`bid`
:x: "integer, unique, randomly generated 8 digit numeric identifier used in linkage to phenotypic data"

:heavy_check_mark:  "Unique 5 digit numeric identifier of all samples collected for an acute test/sample collection period. All samples collected during that period will have the same BID."

I got this description from a "merged_dictionary.txt" file that I had.

**Comment by nicolerg** [comment]
Thank you! I clarified `pid` as well. See: https://motrpac.github.io/MotrpacRatTraining6moData/reference/PHENO.html
