### ISSUE TITLE
`TRNSCRPT_WATSC_NORM_DATA` contains extra rows

### ISSUE THREAD

**Issue by TylerSagendorf** [MoTrPAC/MotrpacRatTraining6moData#41]
It appears that there are 7 additional transcripts in `TRNSCRPT_WATSC_NORM_DATA` that should not be there, assuming the dataset was generated with `MotrpacRatTraining6mo::transcript_normalize_counts`. Unsure if other transcriptomics datasets are similarly affected or what is causing the discrepancy.

```
library(MotrpacRatTraining6moData) # v1.7.0
library(MotrpacRatTraining6mo) # v1.2.0

norm_data <- transcript_normalize_counts("WATSC")
nrow(norm_data) # 16757
nrow(TRNSCRPT_WATSC_NORM_DATA) # 16764 (noted in documentation)

setdiff(TRNSCRPT_WATSC_NORM_DATA$feature_ID, rownames(norm_data))
# [1] "ENSRNOG00000004662" "ENSRNOG00000033186" "ENSRNOG00000045741"
# [4] "ENSRNOG00000047624" "ENSRNOG00000048573" "ENSRNOG00000049020"
# [7] "ENSRNOG00000061816"
```

Suggest including dataset processing scripts in "data-raw" whenever possible to improve reproducibility, though I know this would be time consuming.

**Comment by nicolerg** [comment]
Hi Tyler, nice catch. I am not sure why this is the case. 

All of the scripts used to generate objects in `data/` are available in [inst/scripts](https://r-pkgs.org/misc.html#sec-misc-inst). I include specific links below.

All of the `TRNSCRPT_NORM_DATA` objects were from `gs://motrpac-data-freeze-pass/pass1b-06/v1.1/analysis/transcriptomics/transcript-rna-seq/normalized-data/*normalized-log-cpm*` (see [here](https://github.com/MoTrPAC/MotrpacRatTraining6moData/blob/main/inst/scripts/save_sample_level_data.Rmd#L216)), which have since been moved to `gs://motrpac-data-hub/pass1b-06/analysis/transcriptomics/transcript-rna-seq/normalized-data/*normalized-log-cpm*`. `motrpac_pass1b-06_t70-white-adipose_transcript-rna-seq_normalized-log-cpm.txt` has 16764 genes, same as `TRNSCRPT_WATSC_NORM_DATA`. 

All of the `TRNSCRPT_RAW_COUNTS` objects were from `gs://motrpac-data-freeze-pass/v1.1/results/transcriptomics/*/transcript-rna-seq/motrpac_pass1b-06_*_transcript-rna-seq_rsem-genes-count.txt` (see [here](https://github.com/MoTrPAC/MotrpacRatTraining6moData/blob/main/inst/scripts/save_sample_level_data.Rmd#L469)), which have since been moved to `gs://motrpac-data-hub/pass1b-06/results/transcriptomics/*/transcript-rna-seq/motrpac_pass1b-06_*_transcript-rna-seq_rsem-genes-count.txt`. `motrpac_pass1b-06_t70-white-adipose_transcript-rna-seq_rsem-genes-count.txt` has 32883 genes, same as `TRNSCRPT_WATSC_RAW_COUNTS`. 

I copied `transcript_normalize_counts()` from what I thought was the code that was used to generate these `normalized-log-cpm` files [here](https://github.com/MoTrPAC/motrpac-bic-norm-qc/blob/master/bic_qc_reports/inprogress/pass1b_rnaseq.Rmd#L140) and [here](https://github.com/MoTrPAC/motrpac-bic-norm-qc/blob/master/tools/unsupervised_normalization_functions.R#L99), copied here:
```r
min_cpm = 0.5
min_num_samples = 2
norm_method="TMM"

#' Takes a count matrix compute normalization factors, and
#' return the normalized log cpms.
#' @param x a numeric counts matrix with samples as the columns
edgeR_normalized_log_cpm<-function(x,min_cpm = 0.5,min_num_samples = 2,norm_method="TMM"){
  # raw counts filtered down to samples in this tissue 
  raw_dge = edgeR::DGEList(counts=x) 
  keep = rowSums(cpm(raw_dge) > min_cpm) >= min_num_samples
  filt_dge = raw_dge[keep, , keep.lib.sizes=FALSE]
  
  # filt --> tmm 
  dge = edgeR::calcNormFactors(filt_dge, method=norm_method)
  tmm = edgeR::cpm(dge,log=TRUE)
  
  return(tmm)
}

# exclude low count genes in the current dataset
norm_counts = edgeR_normalized_log_cpm(as.matrix(unnorm_counts),
    min_cpm = min_cpm,
    min_num_samples = min_num_samples,
    norm_method = norm_method
) 
```
Versus the source code for `transcript_normalize_counts()`: 
```r
transcript_normalize_counts = function(tissue, min_cpm = 0.5, min_num_samples = 2, norm_method="TMM"){

  counts = fetch_object(sprintf("TRNSCRPT_%s_RAW_COUNTS", gsub("-","",tissue)))
  rownames(counts) = counts$feature_ID
  counts[,c("feature","feature_ID","tissue","assay")] = NULL
  
  raw_dge = edgeR::DGEList(counts=counts) 
  keep = rowSums(edgeR::cpm(raw_dge) > min_cpm) >= min_num_samples
  filt_dge = raw_dge[keep, , keep.lib.sizes=FALSE]
  
  # filt --> tmm 
  dge = edgeR::calcNormFactors(filt_dge, method=norm_method)
  tmm = edgeR::cpm(dge,log=TRUE)
  
  return(tmm)
}
```
So the code is identical. Which suggests that the `motrpac_pass1b-06_t70-white-adipose_transcript-rna-seq_normalized-log-cpm.txt` files in the data release were actually generated with different code. @archanaraja can you please point me to the script that generates the normalized RNA-seq data in the data release?

**Comment by nicolerg** [comment]
Or maybe @david-dd-amar would know better which script generates the normalized RNA-seq data in the release? e.g. `motrpac_pass1b-06_t70-white-adipose_transcript-rna-seq_normalized-log-cpm.txt`

**Comment by nicolerg** [comment]
Here's a code snippet to demonstrate the equality of the code. So either different raw counts were used as input, which seems unlikely, or a different script was used to generate the normalized data files. 

```r
library(MotrpacRatTraining6mo)
library(MotrpacRatTraining6moData)
library(edgeR)

### use code from motrpac-bic-norm-qc/bic_qc_reports/inprogress/pass1b_rnaseq.Rmd

min_cpm = 0.5
min_num_samples = 2
norm_method="TMM"

#' Takes a count matrix compute normalization factors, and
#' return the normalized log cpms.
#' @param x a numeric counts matrix with samples as the columns
edgeR_normalized_log_cpm<-function(x,min_cpm = 0.5,min_num_samples = 2,norm_method="TMM"){
  # raw counts filtered down to samples in this tissue 
  raw_dge = edgeR::DGEList(counts=x) 
  keep = rowSums(cpm(raw_dge) > min_cpm) >= min_num_samples
  filt_dge = raw_dge[keep, , keep.lib.sizes=FALSE]
  
  # filt --> tmm 
  dge = edgeR::calcNormFactors(filt_dge, method=norm_method)
  tmm = edgeR::cpm(dge,log=TRUE)
  
  return(tmm)
}

unnorm_counts = TRNSCRPT_WATSC_RAW_COUNTS
rownames(unnorm_counts) = unnorm_counts$feature_ID
unnorm_counts[,c("feature","feature_ID","tissue","assay")] = NULL
# exclude low count genes in the current dataset
test1 = edgeR_normalized_log_cpm(as.matrix(unnorm_counts),
                                       min_cpm = min_cpm,
                                       min_num_samples = min_num_samples,
                                       norm_method = norm_method
) 

### use code in MotrpacRatTraining6mo

test2 = transcript_normalize_counts("WAT-SC")

### check equality of results 
all(colnames(test1) == colnames(test2))
all(rownames(test1) == rownames(test2))
all(test1 == test2)
```

**Comment by nicolerg** [comment]
Archana confirmed that the code in the QC report is what was used to generate the normalized RNA-seq tables. From the commit history, I can see that code hasn't changed since May 27, 2020. Normalized RNA-seq data tables were only generated once and moved around to different GCS buckets. So there is no clear explanation for this discrepancy. I am investigating the possibility that the difference is explained by a difference in the `edgeR` version used.

**Comment by archanaraja** [comment]
Like @nicolerg , I did check the raw counts and normalized tables , they were consistent across the releases and never changed but the 7 genes do exist in those tables for WAT-SC. The normalization code didn't seem to change for the rna-seq, my suspicion filtering didn't work as expected between the two versions. (data hub vs Rpackage)??

**Comment by nicolerg** [comment]
> my suspicion filtering didn't work as expected between the two versions 

Right, and we are trying to understand why the filtering didn't work as expected between the two versions when the code is identical.

**Comment by nicolerg** [comment]
`transcript_normalize_counts()` consistently returns fewer genes than `TRNSCRPT_NORM_DATA` (which is the same as the data in the Data Hub):
```r
library(MotrpacRatTraining6mo)
library(MotrpacRatTraining6moData)

# compare number of genes in normalized data in data hub to number of genes returned by transcript_normalize_counts()

for(tissue in TISSUE_ABBREV){
  norm_counts = load_sample_data(tissue, "TRNSCRPT") # same as data hub
  if(is.null(norm_counts)) next
  normalized = transcript_normalize_counts(tissue)
  message(sprintf("N genes in Data Hub: %s\nN genes from transcript_normalize_counts(): %s\nDifference: %s\n",
                  nrow(norm_counts),
                  nrow(normalized),
                  abs(nrow(norm_counts)-nrow(normalized))))
}
```
Result:
```
TRNSCRPT_ADRNL_NORM_DATA
N genes in Data Hub: 15809
N genes from transcript_normalize_counts(): 15792
Difference: 17

TRNSCRPT_BAT_NORM_DATA
N genes in Data Hub: 16154
N genes from transcript_normalize_counts(): 16146
Difference: 8

TRNSCRPT_BLOOD_NORM_DATA
N genes in Data Hub: 13935
N genes from transcript_normalize_counts(): 13922
Difference: 13

TRNSCRPT_COLON_NORM_DATA
N genes in Data Hub: 16556
N genes from transcript_normalize_counts(): 16542
Difference: 14

TRNSCRPT_CORTEX_NORM_DATA
N genes in Data Hub: 16443
N genes from transcript_normalize_counts(): 16408
Difference: 35

TRNSCRPT_HEART_NORM_DATA
N genes in Data Hub: 14445
N genes from transcript_normalize_counts(): 14441
Difference: 4

TRNSCRPT_HIPPOC_NORM_DATA
N genes in Data Hub: 16608
N genes from transcript_normalize_counts(): 16583
Difference: 25

TRNSCRPT_HYPOTH_NORM_DATA
N genes in Data Hub: 16955
N genes from transcript_normalize_counts(): 16937
Difference: 18

TRNSCRPT_KIDNEY_NORM_DATA
N genes in Data Hub: 15981
N genes from transcript_normalize_counts(): 15969
Difference: 12

TRNSCRPT_LIVER_NORM_DATA
N genes in Data Hub: 14437
N genes from transcript_normalize_counts(): 14428
Difference: 9

TRNSCRPT_LUNG_NORM_DATA
N genes in Data Hub: 16505
N genes from transcript_normalize_counts(): 16493
Difference: 12

TRNSCRPT_OVARY_NORM_DATA
N genes in Data Hub: 17035
N genes from transcript_normalize_counts(): 17026
Difference: 9

TRNSCRPT_SKMGN_NORM_DATA
N genes in Data Hub: 13774
N genes from transcript_normalize_counts(): 13765
Difference: 9

TRNSCRPT_SKMVL_NORM_DATA
N genes in Data Hub: 13973
N genes from transcript_normalize_counts(): 13958
Difference: 15

TRNSCRPT_SMLINT_NORM_DATA
N genes in Data Hub: 16411
N genes from transcript_normalize_counts(): 16396
Difference: 15

TRNSCRPT_SPLEEN_NORM_DATA
N genes in Data Hub: 16319
N genes from transcript_normalize_counts(): 16292
Difference: 27

TRNSCRPT_TESTES_NORM_DATA
N genes in Data Hub: 17359
N genes from transcript_normalize_counts(): 17338
Difference: 21

TRNSCRPT_VENACV_NORM_DATA
N genes in Data Hub: 16338
N genes from transcript_normalize_counts(): 16330
Difference: 8

TRNSCRPT_WATSC_NORM_DATA
N genes in Data Hub: 16764
N genes from transcript_normalize_counts(): 16757
Difference: 7
```

**Comment by nicolerg** [comment]
I also get 16757 filtered WAT-SC genes (instead of 16764) with a much older version of edgeR (3.28.1). So I'm at a loss here.

**Comment by nicolerg** [comment]
Unsurprisingly but reassuringly, the genes that are excluded only by `transcript_normalize_counts()` are consistently on the expression threshold. In these plots, black points are genes included in both versions of the normalized data, gray points are genes excluded by both versions of normalized data, and red points are genes included in the normalized data from the Data Hub but excluded by `transcript_normalize_counts()`. 
![missing-genes-WAT-SC](https://user-images.githubusercontent.com/32148717/212215638-ac3b95b2-11a6-4ae7-881e-0d31712fb7ba.png)
![missing-genes-VENACV](https://user-images.githubusercontent.com/32148717/212215640-554f8944-57a9-4a11-99d0-230c34f58433.png)
![missing-genes-TESTES](https://user-images.githubusercontent.com/32148717/212215643-2e7bc849-e1ba-4669-87a5-8849d8080169.png)
![missing-genes-SPLEEN](https://user-images.githubusercontent.com/32148717/212215645-b47767c8-fbfc-4bfe-aab5-812b803f173c.png)
![missing-genes-SMLINT](https://user-images.githubusercontent.com/32148717/212215647-33eff524-e9bd-467a-a7b3-a1964ba679b0.png)
![missing-genes-SKM-VL](https://user-images.githubusercontent.com/32148717/212215649-fa94436d-2917-4e36-8f11-a6ab0d35d32b.png)
![missing-genes-SKM-GN](https://user-images.githubusercontent.com/32148717/212215651-0870d4aa-58cc-4211-8818-8be991465bbe.png)
![missing-genes-OVARY](https://user-images.githubusercontent.com/32148717/212215654-e8de10ac-e247-45ef-86cc-43c1b8547ee8.png)
![missing-genes-LUNG](https://user-images.githubusercontent.com/32148717/212215656-efab2846-d6c8-4683-b556-fe71fea8a511.png)
![missing-genes-LIVER](https://user-images.githubusercontent.com/32148717/212215657-19b6eaf7-08fb-44f8-a7e7-2e811d3be893.png)
![missing-genes-KIDNEY](https://user-images.githubusercontent.com/32148717/212215658-d05cf20b-98fd-4983-8668-38bd00f35944.png)
![missing-genes-HYPOTH](https://user-images.githubusercontent.com/32148717/212215660-05aae726-33be-47b3-9d09-38cfed1e780b.png)
![missing-genes-HIPPOC](https://user-images.githubusercontent.com/32148717/212215663-ebc6ff62-edd8-4057-92e9-90a693799390.png)
![missing-genes-HEART](https://user-images.githubusercontent.com/32148717/212215664-b62ff981-c3f4-4cfe-9491-9bc4bd4335ba.png)
![missing-genes-CORTEX](https://user-images.githubusercontent.com/32148717/212215665-d9583029-0476-42d2-b3da-16cc3b6b95eb.png)
![missing-genes-COLON](https://user-images.githubusercontent.com/32148717/212215668-13e75a6e-3a6a-457e-aba9-9c91965510b9.png)
![missing-genes-BLOOD](https://user-images.githubusercontent.com/32148717/212215669-80c287c3-a72b-4fef-8f1d-6f52597af35b.png)
![missing-genes-BAT](https://user-images.githubusercontent.com/32148717/212215670-785353fd-d078-4fd2-8e90-01e1a9f1c5c3.png)
![missing-genes-ADRNL](https://user-images.githubusercontent.com/32148717/212215671-5cbdf4a7-735f-489a-9f85-d6d74d5def67.png)
```r
library(MotrpacRatTraining6mo)
library(MotrpacRatTraining6moData)
library(data.table)
library(edgeR)
library(ggplot2)

# compare number of genes in normalized data in data hub to number of genes returned by transcript_normalize_counts()


for(tissue in TISSUE_ABBREV){
  norm_counts = load_sample_data(tissue, "TRNSCRPT") # same as data hub
  if(is.null(norm_counts)) next
  normalized = transcript_normalize_counts(tissue)
  # message(sprintf("N genes in Data Hub: %s\nN genes from transcript_normalize_counts(): %s\nDifference: %s\n",
  #                 nrow(norm_counts),
  #                 nrow(normalized),
  #                 abs(nrow(norm_counts)-nrow(normalized))))
  
  # make a plot 
  missing = setdiff(norm_counts$feature_ID, rownames(normalized))
  if(length(setdiff(rownames(normalized), norm_counts$feature_ID)) > 0){
    stop()
  }
  raw_data = df_to_numeric(load_sample_data(tissue, "TRNSCRPT", normalized = FALSE))
  
  min_cpm = 0.5
  min_num_samples = 2
  norm_method="TMM"
  raw_dge = edgeR::DGEList(counts=raw_data) 
  cpm = cpm(raw_dge)
  
  # get mean cpm per gene
  gene_means = data.table(feature_ID = rownames(cpm),
                          mean = rowMeans(cpm),
                          colour = ifelse(rownames(cpm) %in% rownames(norm_data), "black", "gray"))
  gene_means[feature_ID %in% missing, colour := "red"]
  gene_means = gene_means[order(mean)]
  gene_means[,order := 1:nrow(gene_means)]
  png(sprintf("~/Desktop/missing-genes-%s.png",tissue), width=4, height=4, units="in", res=400)
  g = ggplot(data=gene_means, aes(x=order, y=log2(mean), colour=colour)) +
    geom_point(data=gene_means[colour != "red"], size=0.1) +
    theme_bw() +
    geom_point(data=gene_means[colour == "red"]) +
    scale_colour_identity() +
    labs(title=tissue, x="Order", y="Mean CPM per gene (log2)")
  print(g)
  dev.off()
}
```

**Comment by nicolerg** [comment]
Tweaking the parameters (min_cpm = 0.5, min_num_samples = 2) to reasonable other values and changing ">" to ">=" does not give the same number of genes either. So I think the only remaining possibility is that an older version of `edgeR::cpm()` was used to generate the files in the data freeze, and there is some small functional difference that results in a few additional genes being excluded. I will add a note to the docs about this discrepancy but won't investigate this further. 

Notably, these are the only lines of code that are directly involved in filtering raw RNA-seq counts:
```r
keep = rowSums(edgeR::cpm(raw_dge) > min_cpm) >= min_num_samples
filt_dge = raw_dge[keep, , keep.lib.sizes=FALSE]
```
