### ISSUE TITLE
compress data?

### ISSUE THREAD

**Issue by bcjaeger** [MoTrPAC/MotrpacRatTraining6moData#5]
Have you considered using compression on the files in `data/`? This may help with the install timeout issue mentioned in the readme.  I tested this out and compared install times with compression versus without (see below). If you are interested in testing this out too, see `?tools::resaveRdaFiles`. I am happy to initiate a pull request if that would be helpful. 

```
# with compression
system.time(
  remotes::install_github("bcjaeger/MotrpacRatTraining6moData@compress")
)

* DONE (MotrpacRatTraining6moData)
   user  system elapsed 
   1.63    4.51  218.14

# without
system.time(
  remotes::install_github("MoTrPAC/MotrpacRatTraining6moData")
)

* DONE (MotrpacRatTraining6moData)
   user  system elapsed 
   1.67    5.43  323.04 

```

**Comment by nicolerg** [comment]
Thanks, @bcjaeger! What kind/level of compression did you use? All .rda are already compressed with `bzip2`, which is the default behavior for `usethis::use_data()`.

**Comment by nicolerg** [comment]
I was also able to resolve the Mac error by installing the newest version of R and extending the timeout using `options(timeout=1e5)`. I will update the README to reflect this. If people are able to use `install_github("MoTrPAC/MotrpacRatTraining6moData")` on Linux, Mac, and Windows without errors, I am less concerned about the walltime.

**Comment by bcjaeger** [comment]
> I was also able to resolve the Mac error by installing the newest version of R and extending the timeout using options(timeout=1e5)

Awesome!

> What kind/level of compression did you use?

This is a great question - I ran `tools::resaveRDAfiles()` with the default `compress = 'auto'`, which asks R to choose the compression type. It will try "gzip", "bzip2" and if the "gzip" compressed size is over 10Kb, "xz" and choose the smallest compressed file (but with a 10% bias towards "gzip"). So it is possible that some files may have been compressed in different ways. If it is still helpful to work on lowering install/load times, I would like to run a few more benchmarks to see if things load slower from the lazy database when I  am using the compressed files in my branch (the 'compress' in my forked repo) versus the compressed files in the main branch. I should also re-run the benchmark above a few times and perhaps on different systems to see if there is something else that explains the timing difference.

**Comment by nicolerg** [comment]
>If it is still helpful to work on lowering install/load times, I would like to run a few more benchmarks to see if things load slower from the lazy database when I am using the compressed files in my branch (the 'compress' in my forked repo) versus the compressed files in the main branch. I should also re-run the benchmark above a few times and perhaps on different systems to see if there is something else that explains the timing difference.

That sounds great! Thanks for your help.

**Comment by bcjaeger** [comment]
Update: I ran the same installation benchmarks on a mac to compare install time using the compressed branch versus the main branch. I'm happy to report the compressed branch was installed about 2 and a half minutes faster. I still need to check some benchmarks for loading files into one's environment using the compressed branch versus the main branch. I'm worried that the files in the compressed branch may take longer to load in this comparison.

**Comment by nicolerg** [comment]
That's a massive improvement! The largest .rda file is `FEATURE_TO_GENE` if you want to test object loading time with that.

**Comment by nicolerg** [comment]
@bcjaeger I gave you write permissions for the repo, so please feel free to submit a PR to merge a branch with an optimally compressed version of the data into `main`. Please add whatever code you use to change the compression to a new script in `inst/scripts`

**Comment by bcjaeger** [comment]
Excellent! Sorry I have been out of the loop this week (I've been at the Joint Statistical Meetings [JSM]). 

Some good news from the benchmarks I ran:

_before_ compression:

```
> system.time(data("FEATURE_TO_GENE"))
   user  system elapsed 
  14.72    0.17   14.89 
```

_after_:

```
> system.time(data("FEATURE_TO_GENE"))
   user  system elapsed 
  10.77    0.15   10.93 
```

So I think we can proceed! I will include the script in `inst` as you mentioned and open the pull request shortly.

**Comment by nicolerg** [comment]
Implementing data compression in a new branch now
